name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
       # --- Release steps (only run when this is a tag build) ---
    - name: Publish app
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        dotnet publish --configuration Release -o publish
        (cd publish && zip -r ../TcpFuzzClient-${{ github.ref_name }}.zip .)
        ls -lh TcpFuzzClient-${{ github.ref_name }}.zip
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          TcpFuzzClient-${{ github.ref_name }}.zip
